---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  APP_ENV: "development"
  API_URL: "http://api.example.com"
  PORT: "8080"
  DEBUG: "true"

###
# kubectl create configmap app-config \
#    --from-literal=API_URL=http://api.example.com \
#    --from-literal=PORT=8080
#
###

###
# ConfigMap with items
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: demo-config
#data:
#  some-cool.json: |
#    {
#      "key1": "val1",
#      "key2": "val2"
#    }
#  another-yaml.yaml: |
#    fruits:
#      - banana
#      - apple
#      - orange